replicaCount: 1
image:
  repository: ghcr.io/bogdankam41/shop-app
  tag: 75025989b15343524ea45493abcfb2d85ff3ccb0
resources: {}
ingress:
  host: dev.shop.local

networkPolicy:
  enabled: false
  denyEgress: false

ghcrPull:
  sealed: false
