replicaCount: 1
image:
  repository: ghcr.io/bogdankam41/shop-app
  tag: 2e506b66caa0836570a9340037de25842376d9e5
resources: {}
ingress:
  host: dev.shop.local

networkPolicy:
  enabled: false
  denyEgress: false

ghcrPull:
  sealed: false
