replicaCount: 1
image:
  repository: ghcr.io/bogdankam41/shop-app
  tag: 8ce464f8a6fb2fb22765d1eb094849a92f9dc5b3
resources: {}
ingress:
  host: dev.shop.local

networkPolicy:
  enabled: false
  denyEgress: false

ghcrPull:
  sealed: false
